package com.backend.social.enums;

public enum ErrorCode {

    USER_ALREADY_EXISTS,
    RESOURCE_NOT_FOUND,
    UNAUTHORIZED,
    SELF_DELETE_NOT_ALLOWED,
    VALIDATION_FAILED,
    INVALID_REQUEST_BODY,
    FILE_SIZE_EXCEEDED,
    INTERNAL_SERVER_ERROR,
    ACCOUNT_NOT_BLOCKED,
    UNVERIFIED_ACCOUNT,
    COOLDOWN_ACTIVE,
    INVALID_PASSWORD,
    INVALID_OTP, INVALID_CREDENTIALS, INACTIVE_ACCOUNT, INVALID_TOKEN, TOKEN_EXPIRED, INVALID_CONTENT, LIMIT_EXCEEDED
}
